name: 'JIRA - Raise Change'

on:
  workflow_call:
    inputs:
      gha_env:
        required: true
        type: string

      azure_env:
        required: true
        type: string

    secrets:
      jira_base_url:
      jira_user_email:
      jira_api_token:
        required: true

#env:
#  PROJECT_NAME: jira-automation-poc
#  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src'
#  DOTNET_VERSION: '6.x'

jobs:        
    build:
        runs-on: ubuntu-latest
        name: Jira Example
        steps:
            - name: Login
              uses: atlassian/gajira-login@master
              env:
                JIRA_BASE_URL: ${{ secrets.jira_base_url }}
                JIRA_USER_EMAIL: ${{ secrets.jira_user_email }}
                JIRA_API_TOKEN: ${{ secrets.jira_api_token }}

            - name: Create
              id: create
              uses: atlassian/gajira-create@master
              with:
                project: SD
                issuetype: Change
                summary: |
                  Change raise for JIRA POC
                description: |
                  Change description goes here
                fields: '{"customfield_13658 ": "Insurance", "customfield_13621 ": "Standard", "customfield_13624 ": "2022-11-18", "customfield_13625 ": "2022-11-18", "customfield_13665": "No Impact"}'
            - name: Log created issue
              run: echo "Issue ${{ steps.create.outputs.issue }} was created"
